# Generated by Django 2.1.15 on 2021-01-06 00:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Supervisor'), (3, 'Manager')], null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='zip',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
