# Generated by Django 2.1.15 on 2021-02-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210105_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='IT',
            field=models.BooleanField(default=True, null=True, verbose_name='IT'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts',
            field=models.BooleanField(default=True, null=True, verbose_name='alerts'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='help',
            field=models.BooleanField(default=True, null=True, verbose_name='help'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='management',
            field=models.BooleanField(default=True, null=True, verbose_name='management'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='marketing',
            field=models.BooleanField(default=True, null=True, verbose_name='marketing'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='social_media',
            field=models.BooleanField(default=True, null=True, verbose_name='social_media'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='web_monitor',
            field=models.BooleanField(default=True, null=True, verbose_name='web_monitor'),
        ),
    ]
