# Generated by Django 2.1.15 on 2021-02-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210203_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='alerts_accounting',
            field=models.BooleanField(default=False, null=True, verbose_name='alerts_accounting'),
        ),
    ]
