# Generated by Django 3.1.6 on 2021-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofileinfo_alerts_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
