# Generated by Django 3.1.6 on 2021-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210215_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address_line2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
