from django.db import models
from datetime import datetime

class ChargeCodes(models.Model):
    id = models.AutoField(primary_key=True)
    ResourceID = models.CharField("resource id",max_length=100,null=True,unique=False,default='N/A') 
    Customer = models.CharField("customer",max_length=100,null=True,unique=False,default='N/A') 
    ChargeCode = models.CharField("charge code",max_length=100,null=True,unique=False,default='N/A') 
    Products_Services = models.CharField("products services",max_length=100,null=True,unique=False,default='N/A') 
    ChargeDate = models.CharField("charge date",max_length=100,null=True,unique=False,default='N/A') 
    Client = models.CharField("client",max_length=100,null=True,unique=False,default='N/A') 
    last_update = models.DateField(null=True)
    backup_index = models.IntegerField(null=True,unique=False)

class ClassCodes(models.Model):
    id = models.AutoField(primary_key=True)
    ClassCode = models.CharField("class code",max_length=50,null=True,unique=False,default='N/A') 
    InventoryClass = models.CharField("inv class",max_length=50,null=True,unique=False,default='N/A') 
    Client = models.CharField("client",max_length=50,null=True,unique=False,default='N/A') 
    last_update = models.DateField(null=True)
    backup_index = models.IntegerField(null=True,unique=False)
    
class Expenses(models.Model):
    id = models.AutoField(primary_key=True)
    vendor_id = models.CharField("vendor id",max_length=50,null=True,unique=False,default='N/A') 
    expense_type = models.CharField("expense type",max_length=50,null=True,unique=False,default='N/A') 
    expense_description = models.CharField("expense desc",max_length=355,null=True,unique=False,default='N/A') 
    sale_date = models.DateTimeField(default=datetime.now, blank=True)
    item = models.CharField("item",max_length=50,null=True,unique=False,default='N/A') 
    item_desc = models.CharField("item desc",max_length=355,null=True,unique=False,default='N/A') 
    quantity = models.CharField("quantity",max_length=50,null=True,unique=False,default='N/A') 
    item_cost = models.CharField("item cost",max_length=50,null=True,unique=False,default='N/A') 
    total_cost = models.CharField("total cost",max_length=50,null=True,unique=False,default='N/A') 
    reoccuuring_expenses = models.BooleanField("reoccuuring_expenses",unique=False,null=True,default=False)
    reoccuring_interval = models.CharField("reoccuring interval",max_length=255,null=True,unique=False,default='N/A') 
    invoice_id = models.CharField("invoiceID",max_length=255,null=True,unique=False,default='N/A') 
    operator = models.CharField("staff id",max_length=50,null=True,unique=False,default='N/A') 
    last_update = models.DateField(null=True) 
    backup_index = models.IntegerField(null=True,unique=False)
    
class Invoice(models.Model):
    id = models.AutoField(primary_key=True)
    InvoiceID = models.IntegerField(null=True,unique=False)
    ResourceID = models.IntegerField(null=True,unique=False)
    CustomerID = models.IntegerField(null=True,unique=False)
    ResourceName = models.CharField("resource name",max_length=100,null=True,unique=False,default='N/A')
    ResourceType = models.CharField("resource type",max_length=100,null=True,unique=False,default='N/A')
    ResourceDept = models.CharField("resource dept",max_length=100,null=True,unique=False,default='N/A')
    InvoiceDate = models.DateField(null=True)
    ChargeCode = models.CharField("charge code",max_length=100,null=True,unique=False,default='N/A')
    Quantity = models.FloatField("quantity",null=True,unique=False) 
    Rate = models.FloatField("rate",null=True,unique=False) 
    Total = models.FloatField("total",null=True,unique=False) 
    Client = models.CharField("client",max_length=50,null=True,unique=False,default='N/A')
    StaffID = models.CharField("staff id",max_length=50,null=True,unique=False,default='N/A')
    last_update = models.DateField(null=True)
    backup_index = models.IntegerField(null=True,unique=False)

class InvoiceID(models.Model):
    id = models.AutoField(primary_key=True)
    InvoiceReference = models.CharField("invoice ref",max_length=50,null=True,unique=False,default='N/A')
    Customer = models.CharField("customer",max_length=50,null=True,unique=False,default='N/A')
    InvoiceDate = models.DateField(null=True)
    Paid = models.BooleanField("paid",unique=False,null=True,default=True)
    Client = models.CharField("client",max_length=50,null=True,unique=False,default='N/A')
    last_update = models.DateField(null=True)
    backup_index = models.IntegerField(null=True,unique=False)
    
class Contractor_Quote(models.Model):
    id = models.AutoField(primary_key=True)
    InvoiceID = models.IntegerField(null=True,unique=False)
    ResourceID = models.IntegerField(null=True,unique=False)
    CustomerID = models.IntegerField(null=True,unique=False)
    ResourceName = models.CharField("resource name",max_length=100,null=True,unique=False,default='N/A')
    ResourceType = models.CharField("resource type",max_length=100,null=True,unique=False,default='N/A')
    ResourceDept = models.CharField("resource dept",max_length=100,null=True,unique=False,default='N/A')
    InvoiceDate = models.DateField(null=True)
    ChargeCode = models.CharField("charge code",max_length=100,null=True,unique=False,default='N/A')
    Quantity = models.FloatField("quantity",null=True,unique=False) 
    Rate = models.FloatField("rate",null=True,unique=False) 
    Total = models.FloatField("total",null=True,unique=False) 
    Client = models.CharField("client",max_length=50,null=True,unique=False,default='N/A')
    StaffID = models.CharField("staff id",max_length=50,null=True,unique=False,default='N/A')
    last_update = models.DateField(null=True) 
    backup_index = models.IntegerField(null=True,unique=False)    
    
class Contractor_QuoteID(models.Model):
    id = models.AutoField(primary_key=True)
    InvoiceReference = models.CharField("invoice ref",max_length=50,null=True,unique=False,default='N/A')
    Customer = models.CharField("customer",max_length=50,null=True,unique=False,default='N/A')
    InvoiceDate = models.DateField(null=True)
    Paid = models.BooleanField("paid",unique=False,null=True,default=True)
    Client = models.CharField("client",max_length=50,null=True,unique=False,default='N/A')
    last_update = models.DateField(null=True)  
    backup_index = models.IntegerField(null=True,unique=False)    
     

class ZipCode(models.Model):
    id = models.AutoField(primary_key=True)
    ZipCode = models.CharField("ZipCode",max_length=50,null=True,unique=False,default='N/A')
    PlaceName = models.CharField("PlaceName",max_length=50,null=True,unique=False,default='N/A')
    StateAbreviation = models.CharField("StateAbreviation",max_length=50,null=True,unique=False,default='N/A')
    County = models.CharField("County",max_length=50,null=True,unique=False,default='N/A')
    Latitude = models.CharField("Latitude",max_length=50,null=True,unique=False,default='N/A')
    Longitude = models.CharField("Longitude",max_length=50,null=True,unique=False,default='N/A')
    StateTax = models.DecimalField("StateTax",max_digits=10, decimal_places=2,null=True,unique=False)
    LocalTax = models.DecimalField("LocalTax",max_digits=10, decimal_places=2,null=True,unique=False)
    TotalTax = models.DecimalField("TotalTax",max_digits=10, decimal_places=2,null=True,unique=False)
    FiscalDate = models.DateField(null=True) 
    backup_index = models.IntegerField(null=True,unique=False)    
