from django.db import models

class Clients(models.Model):
    id = models.AutoField(primary_key=True)
    FirstName = models.CharField("First Name",max_length=255,null=True,unique=False,default='N/A') 
    LastName = models.CharField("last name",max_length=255,null=True,unique=False,default='N/A') 
    StreetAddress = models.CharField("street address",max_length=255,null=True,unique=False,default='N/A') 
    City = models.CharField("city",max_length=255,null=True,unique=False,default='N/A') 
    State = models.CharField("state",max_length=50,null=True,unique=False,default='N/A')  
    ZipCode = models.CharField("zip code",max_length=50,null=True,unique=False,default='N/A')  
    PhoneNumber = models.CharField("phone number",max_length=50,null=True,unique=False,default='N/A')  
    EmailAddress = models.CharField("email",max_length=255,null=True,unique=False,default='N/A')  
    CustomerType = models.CharField("customer type",max_length=255,null=True,unique=False,default='N/A')  
    TaxIDNumber = models.CharField("tax id",max_length=50,null=True,unique=False,default='N/A') 
    ShipStreet = models.CharField("ship street",max_length=100,null=True,unique=False,default='N/A')  
    ShipCity = models.CharField("ship city",max_length=50,null=True,unique=False,default='N/A')  
    ShipState = models.CharField("shipstate",max_length=50,null=True,unique=False,default='N/A')  
    ShipZip = models.CharField("ship zip",max_length=50,null=True,unique=False,default='N/A')      
    Unsubscribe = models.BooleanField("active",unique=False,null=True,default=True)
    ProfitabilityScale = models.CharField("ship zip",max_length=50,null=True,unique=False,default='N/A') 
    Business = models.CharField("ship zip",max_length=50,null=True,unique=False,default='N/A') 
    BusinessName = models.CharField("ship zip",max_length=255,null=True,unique=False,default='N/A') 
    Client = models.CharField("ship zip",max_length=50,null=True,unique=False,default='N/A')
    last_update = models.DateField(null=True)    
    backup_index = models.IntegerField(null=True,unique=False)