# Generated by Django 2.1.15 on 2021-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20210117_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehical',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vehicle_fuel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle_insurance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle_mantainance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle_oil',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle_repair',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle_tire',
            name='name',
        ),
        migrations.AddField(
            model_name='vehical',
            name='make',
            field=models.CharField(default='N/A', max_length=50, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehical',
            name='original_miles',
            field=models.FloatField(null=True, verbose_name='active_miles'),
        ),
        migrations.AddField(
            model_name='vehicle_fuel',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehicle_insurance',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehicle_mantainance',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehicle_oil',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehicle_repair',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AddField(
            model_name='vehicle_tire',
            name='make',
            field=models.CharField(max_length=50, null=True, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='vehical',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
    ]
