# Generated by Django 2.1.15 on 2021-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210117_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_fuel',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='vehicle_insurance',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='vehicle_load',
            name='oil',
        ),
        migrations.RemoveField(
            model_name='vehicle_mantainance',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='vehicle_oil',
            name='oil',
        ),
        migrations.RemoveField(
            model_name='vehicle_repair',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='vehicle_tire',
            name='tires',
        ),
        migrations.DeleteModel(
            name='Vehicle_Fuel',
        ),
        migrations.DeleteModel(
            name='Vehicle_Insurance',
        ),
        migrations.DeleteModel(
            name='Vehicle_load',
        ),
        migrations.DeleteModel(
            name='Vehicle_mantainance',
        ),
        migrations.DeleteModel(
            name='Vehicle_oil',
        ),
        migrations.DeleteModel(
            name='Vehicle_repair',
        ),
        migrations.DeleteModel(
            name='Vehicle_Tire',
        ),
    ]
