# Generated by Django 2.1.15 on 2021-01-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20210117_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical',
            name='original_miles',
            field=models.FloatField(null=True, verbose_name='original_miles'),
        ),
    ]
