# Generated by Django 2.1.15 on 2021-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210117_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehical',
            name='load_limit',
            field=models.FloatField(null=True, verbose_name='load_limit'),
        ),
        migrations.AddField(
            model_name='vehical',
            name='original_value',
            field=models.FloatField(null=True, verbose_name='original_value'),
        ),
    ]
