# Generated by Django 2.1.15 on 2021-01-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20210117_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building',
        ),
        migrations.RemoveField(
            model_name='building_fuel',
            name='building_fuel',
        ),
        migrations.RemoveField(
            model_name='building_repair',
            name='repair',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='internet',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='power',
            name='power',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Building_Fuel',
        ),
        migrations.DeleteModel(
            name='Building_repair',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Internet',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Power',
        ),
    ]
