# Generated by Django 2.1.15 on 2021-01-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210121_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building_mantainance',
            name='repair',
        ),
        migrations.DeleteModel(
            name='Building_mantainance',
        ),
    ]
