# Generated by Django 2.1.15 on 2021-01-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20210121_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_space',
            name='name',
        ),
        migrations.AddField(
            model_name='business_space',
            name='building',
            field=models.CharField(default='N/A', max_length=50, verbose_name='type'),
        ),
    ]
