# Generated by Django 2.1.15 on 2021-01-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20210121_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_space',
            name='last_update',
            field=models.DateField(null=True),
        ),
    ]
