# Generated by Django 2.1.15 on 2021-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_business_space_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_space',
            name='building',
            field=models.CharField(default='N/A', max_length=50, verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehical',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
