# Generated by Django 2.1.15 on 2021-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20210123_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_space',
            name='fuel_cost',
            field=models.FloatField(default=100, null=True, verbose_name='fuel_cost'),
        ),
        migrations.AddField(
            model_name='business_space',
            name='internet_cost',
            field=models.FloatField(default=100, null=True, verbose_name='internet_cost'),
        ),
        migrations.AddField(
            model_name='business_space',
            name='maintenance_cost',
            field=models.FloatField(default=100, null=True, verbose_name='maintenance_cost'),
        ),
        migrations.AddField(
            model_name='business_space',
            name='payment_cost',
            field=models.FloatField(default=100, null=True, verbose_name='payment_cost'),
        ),
        migrations.AddField(
            model_name='business_space',
            name='power_cost',
            field=models.FloatField(default=100, null=True, verbose_name='power_cost'),
        ),
        migrations.AddField(
            model_name='business_space',
            name='sqr_feet',
            field=models.FloatField(default=100, null=True, verbose_name='sqr_feet'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='fuel_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='fuel_percentage'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='insurance_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='insurance_percentage'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='internet_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='power_percentage'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='power_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='power_percent'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='space_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='space_percentage'),
        ),
    ]
