# Generated by Django 2.1.15 on 2021-01-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20210123_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehical',
            name='business_use',
            field=models.BooleanField(default=False, verbose_name='business_use'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='internet_percentage',
            field=models.FloatField(default=0, null=True, verbose_name='internet_percentage'),
        ),
    ]
