# Generated by Django 3.1.6 on 2021-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20210126_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
