# Generated by Django 3.1.6 on 2021-02-21 20:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20210220_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_space',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='vehical',
            name='image_file',
        ),
        migrations.AddField(
            model_name='business_space',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='business'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='personnel'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='product'),
        ),
        migrations.AddField(
            model_name='vehical',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='vehicles'),
        ),
    ]
