# Generated by Django 3.1.6 on 2021-02-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_auto_20210221_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_space',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='business_space',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehical',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehical',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
