# Generated by Django 3.1.6 on 2021-03-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_auto_20210228_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct_Insurance',
            new_name='Product_Insurance',
        ),
        migrations.RenameModel(
            old_name='Prouct_Storage',
            new_name='Product_shipping',
        ),
        migrations.RenameModel(
            old_name='Prouct_shipping',
            new_name='Product_Storage',
        ),
        migrations.AlterField(
            model_name='vehical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
