# Generated by Django 3.1.6 on 2021-03-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_auto_20210303_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_space',
            name='building',
            field=models.CharField(default='N/A', max_length=50, verbose_name='buildings'),
        ),
        migrations.AlterField(
            model_name='business_space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
