# Generated by Django 3.1.6 on 2021-02-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='image',
        ),
        migrations.AddField(
            model_name='barcodes',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
