# Generated by Django 3.1.6 on 2021-02-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0002_auto_20210216_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='inventory_id',
        ),
    ]
