# Generated by Django 3.1.6 on 2021-02-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0004_auto_20210218_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodes',
            old_name='barcode',
            new_name='image',
        ),
    ]
