# Generated by Django 2.1.15 on 2020-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='N/A', max_length=255, null=True, verbose_name='First Name')),
                ('LastName', models.CharField(default='N/A', max_length=255, null=True, verbose_name='last name')),
                ('StreetAddress', models.CharField(default='N/A', max_length=255, null=True, verbose_name='street address')),
                ('City', models.CharField(default='N/A', max_length=255, null=True, verbose_name='city')),
                ('State', models.CharField(default='N/A', max_length=50, null=True, verbose_name='state')),
                ('ZipCode', models.CharField(default='N/A', max_length=50, null=True, verbose_name='zip code')),
                ('PhoneNumber', models.CharField(default='N/A', max_length=50, null=True, verbose_name='phone number')),
                ('EmailAddress', models.CharField(default='N/A', max_length=255, null=True, verbose_name='email')),
                ('CustomerType', models.CharField(default='N/A', max_length=255, null=True, verbose_name='customer type')),
                ('TaxIDNumber', models.CharField(default='N/A', max_length=50, null=True, verbose_name='tax id')),
                ('ShipStreet', models.CharField(default='N/A', max_length=100, null=True, verbose_name='ship street')),
                ('ShipCity', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ship city')),
                ('ShipState', models.CharField(default='N/A', max_length=50, null=True, verbose_name='shipstate')),
                ('ShipZip', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ship zip')),
                ('Unsubscribe', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('ProfitabilityScale', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ship zip')),
                ('Business', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ship zip')),
                ('BusinessName', models.CharField(default='N/A', max_length=255, null=True, verbose_name='ship zip')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ship zip')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
    ]
