# Generated by Django 2.1.15 on 2020-12-30 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_str', models.CharField(max_length=100, verbose_name='charge_type')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('alert_type', models.CharField(max_length=50, verbose_name='product')),
                ('message', models.CharField(max_length=200, verbose_name='product')),
                ('last_update', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(null=True)),
                ('month_str', models.CharField(max_length=100, verbose_name='charge_type')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('income_paid', models.FloatField(null=True, verbose_name='income_paid')),
                ('income_unpaid', models.FloatField(null=True, verbose_name='income_unpaid')),
                ('income_total', models.FloatField(null=True, verbose_name='income')),
                ('expense', models.FloatField(max_length=100, null=True, verbose_name='expense')),
                ('last_update', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExpense_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(null=True)),
                ('month_str', models.CharField(max_length=100, verbose_name='charge_type')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('income_paid', models.FloatField(null=True, verbose_name='income_paid')),
                ('income_unpaid', models.FloatField(null=True, verbose_name='income_unpaid')),
                ('income_total', models.FloatField(null=True, verbose_name='income')),
                ('expense', models.FloatField(max_length=100, null=True, verbose_name='expense')),
                ('last_update', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(null=True)),
                ('month_str', models.CharField(max_length=100, verbose_name='charge_type')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('product', models.CharField(max_length=100, verbose_name='product')),
                ('income', models.FloatField(null=True, verbose_name='income_paid')),
            ],
        ),
    ]
