# Generated by Django 2.1.15 on 2020-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
