# Generated by Django 2.1.15 on 2021-01-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201226_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeCode',
        ),
    ]
