# Generated by Django 2.1.15 on 2021-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_chargecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(null=True)),
                ('staff_id', models.IntegerField(null=True)),
                ('invoice_desc', models.CharField(default='N/A', max_length=100, null=True, verbose_name='invoice_desc')),
                ('charge_code', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource name')),
                ('paid', models.BooleanField(default=False, null=True, verbose_name='paid')),
                ('quote_date', models.DateField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('total', models.FloatField(null=True, verbose_name='total')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(null=True)),
                ('charge_id', models.IntegerField(null=True)),
                ('contractor_id', models.IntegerField(null=True)),
                ('resource_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource type')),
                ('service_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='service type')),
                ('service_provider', models.CharField(default='N/A', max_length=100, null=True, verbose_name='service provider')),
                ('cost_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='cost type')),
                ('item_date', models.DateField(null=True)),
                ('item_desc', models.CharField(default='N/A', max_length=100, null=True, verbose_name='item description')),
                ('rate', models.FloatField(null=True, verbose_name='rate')),
                ('quantity', models.FloatField(null=True)),
                ('total', models.FloatField(null=True, verbose_name='total')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('last_update', models.DateField(null=True)),
                ('invoice_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contractor_Quote',
        ),
        migrations.DeleteModel(
            name='Contractor_QuoteID',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
