# Generated by Django 2.1.15 on 2021-01-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210117_1232'),
        ('accounts', '0005_expenses_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='oil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='tires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='assets.Vehical'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='assets.Vehical'),
        ),
    ]
