# Generated by Django 2.1.15 on 2021-01-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210117_1329'),
        ('accounts', '0006_auto_20210117_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='oil',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='tires',
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_fuel', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_insurance', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_maintaince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_maintaince', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_oil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_oil', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_repair', to='assets.Vehical'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_tires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_tires', to='assets.Vehical'),
        ),
    ]
