# Generated by Django 2.1.15 on 2021-01-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20210117_2154'),
        ('accounts', '0008_expenses_v_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='v_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_fees', to='assets.Vehical'),
        ),
    ]
