# Generated by Django 2.1.15 on 2021-01-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210121_1925'),
        ('accounts', '0010_expenses_v_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='b_fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_fuel', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_insurance', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_internet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_internet', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_mantenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_mantenance', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_phone', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_power', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='b_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_repair', to='assets.Business_Space'),
        ),
    ]
