# Generated by Django 2.1.15 on 2021-01-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_expenses_b_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='b_power',
            new_name='b_utilities',
        ),
    ]
