# Generated by Django 2.1.15 on 2021-01-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20210123_1422'),
        ('accounts', '0014_expenses_b_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='b_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_interest', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='v_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_interest', to='assets.Business_Space'),
        ),
    ]
