# Generated by Django 3.1.6 on 2021-04-11 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210328_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='sale_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
