# Generated by Django 3.1.6 on 2021-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
