from django.contrib import admin
from .models import Personnel, Personnel_Insurance, Personnel_Overhead, Product, Prouct_Storage, Prouct_shipping, Prouct_Insurance,Vehical,Vehicle_Insurance,Vehicle_Fuel,Vehicle_Tire,Vehicle_oil,Vehicle_repair,Vehicle_mantainance,Vehicle_load,Business_Space,Building,Insurance,Power,Internet,Building_Fuel,Phone,Building_repair,Building_mantainance
admin.site.register(Personnel)
admin.site.register(Personnel_Insurance)
admin.site.register(Personnel_Overhead)
admin.site.register(Product)
admin.site.register(Prouct_Storage)
admin.site.register(Prouct_Insurance)
admin.site.register(Vehical)
admin.site.register(Vehicle_Insurance)
admin.site.register(Vehicle_Fuel)
admin.site.register(Vehicle_Tire)
admin.site.register(Vehicle_oil)
admin.site.register(Vehicle_repair)
admin.site.register(Vehicle_mantainance)
admin.site.register(Vehicle_load)
admin.site.register(Business_Space)
admin.site.register(Building)
admin.site.register(Insurance)
admin.site.register(Power)
admin.site.register(Internet)
admin.site.register(Building_Fuel)
admin.site.register(Phone)
admin.site.register(Building_repair)
admin.site.register(Building_mantainance)
