# Generated by Django 2.1.15 on 2020-12-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='client_id',
            new_name='customer_id',
        ),
    ]
