# Generated by Django 2.1.15 on 2020-12-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='active',
            new_name='c_active',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='address',
            new_name='c_address',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='city',
            new_name='c_city',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='created_on',
            new_name='c_created_on',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='email',
            new_name='c_email',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='image_file',
            new_name='c_image_file',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='inventory_id',
            new_name='c_inventory_id',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='last_entry',
            new_name='c_last_entry',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='lat',
            new_name='c_lat',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='lng',
            new_name='c_lng',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='phone',
            new_name='c_phone',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='shelf',
            new_name='c_shelf',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='state',
            new_name='c_state',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='website',
            new_name='c_website',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='zip_code',
            new_name='c_zip_code',
        ),
    ]
