# Generated by Django 2.1.15 on 2020-12-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20201212_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='c_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_image_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_inventory_id',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_last_entry',
            new_name='last_entry',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_lng',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_shelf',
            new_name='shelf',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='c_zip_code',
            new_name='zip_code',
        ),
    ]
