# Generated by Django 2.1.15 on 2021-01-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210121_1925'),
        ('locations', '0002_auto_20210109_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Business_Space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Business_Space', to='assets.Business_Space'),
        ),
        migrations.AddField(
            model_name='location',
            name='cost',
            field=models.FloatField(null=True, verbose_name='cost'),
        ),
    ]
