# Generated by Django 2.1.15 on 2021-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210121_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
