# Generated by Django 3.1.6 on 2021-02-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atspublic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(blank=True, max_length=50, verbose_name='visitor')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='email')),
                ('session_id', models.CharField(blank=True, max_length=50, verbose_name='session_id')),
                ('client_id', models.CharField(blank=True, max_length=50, verbose_name='client_id')),
                ('user_agent', models.CharField(blank=True, max_length=100, verbose_name='user_agent')),
                ('user_ip', models.CharField(blank=True, max_length=100, verbose_name='visitor_ip')),
                ('blocked', models.BooleanField(default=False, null=True, verbose_name='blocked')),
                ('created_on', models.DateField(null=True)),
                ('last_entry', models.DateField(null=True)),
            ],
        ),
    ]
