# Generated by Django 3.1.6 on 2021-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atspublic', '0004_auto_20210206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='client_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='user_agent'),
        ),
    ]
