# Generated by Django 2.1.15 on 2020-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceID', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource id')),
                ('Customer', models.CharField(default='N/A', max_length=100, null=True, verbose_name='customer')),
                ('ChargeCode', models.CharField(default='N/A', max_length=100, null=True, verbose_name='charge code')),
                ('Products_Services', models.CharField(default='N/A', max_length=100, null=True, verbose_name='products services')),
                ('ChargeDate', models.CharField(default='N/A', max_length=100, null=True, verbose_name='charge date')),
                ('Client', models.CharField(default='N/A', max_length=100, null=True, verbose_name='client')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ClassCode', models.CharField(default='N/A', max_length=50, null=True, verbose_name='class code')),
                ('InventoryClass', models.CharField(default='N/A', max_length=50, null=True, verbose_name='inv class')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor_Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceID', models.IntegerField(null=True)),
                ('ResourceID', models.IntegerField(null=True)),
                ('CustomerID', models.IntegerField(null=True)),
                ('ResourceName', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource name')),
                ('ResourceType', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource type')),
                ('ResourceDept', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource dept')),
                ('InvoiceDate', models.DateField(null=True)),
                ('ChargeCode', models.CharField(default='N/A', max_length=100, null=True, verbose_name='charge code')),
                ('Quantity', models.FloatField(null=True, verbose_name='quantity')),
                ('Rate', models.FloatField(null=True, verbose_name='rate')),
                ('Total', models.FloatField(null=True, verbose_name='total')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('StaffID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='staff id')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor_QuoteID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceReference', models.CharField(default='N/A', max_length=50, null=True, verbose_name='invoice ref')),
                ('Customer', models.CharField(default='N/A', max_length=50, null=True, verbose_name='customer')),
                ('InvoiceDate', models.DateField(null=True)),
                ('Paid', models.BooleanField(default=True, null=True, verbose_name='paid')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='vendor id')),
                ('ExpenseType', models.CharField(default='N/A', max_length=50, null=True, verbose_name='expense type')),
                ('ExpenseDescription', models.CharField(default='N/A', max_length=355, null=True, verbose_name='expense desc')),
                ('SaleDate', models.CharField(default='N/A', max_length=50, null=True, verbose_name='sale date')),
                ('Item', models.CharField(default='N/A', max_length=50, null=True, verbose_name='item')),
                ('ItemDescription', models.CharField(default='N/A', max_length=355, null=True, verbose_name='item desc')),
                ('Quantity', models.CharField(default='N/A', max_length=50, null=True, verbose_name='quantity')),
                ('ItemCost', models.CharField(default='N/A', max_length=50, null=True, verbose_name='item cost')),
                ('TotalCost', models.CharField(default='N/A', max_length=50, null=True, verbose_name='total cost')),
                ('ReOccurringExpenses', models.CharField(default='N/A', max_length=255, null=True, verbose_name='reoccuring expenses')),
                ('ReOccurringInterval', models.CharField(default='N/A', max_length=255, null=True, verbose_name='reoccuring interval')),
                ('Client', models.CharField(default='N/A', max_length=255, null=True, verbose_name='client')),
                ('InvoiceID', models.CharField(default='N/A', max_length=255, null=True, verbose_name='invoiceID')),
                ('StaffID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='staff id')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceID', models.IntegerField(null=True)),
                ('ResourceID', models.IntegerField(null=True)),
                ('CustomerID', models.IntegerField(null=True)),
                ('ResourceName', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource name')),
                ('ResourceType', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource type')),
                ('ResourceDept', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource dept')),
                ('InvoiceDate', models.DateField(null=True)),
                ('ChargeCode', models.CharField(default='N/A', max_length=100, null=True, verbose_name='charge code')),
                ('Quantity', models.FloatField(null=True, verbose_name='quantity')),
                ('Rate', models.FloatField(null=True, verbose_name='rate')),
                ('Total', models.FloatField(null=True, verbose_name='total')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('StaffID', models.CharField(default='N/A', max_length=50, null=True, verbose_name='staff id')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceReference', models.CharField(default='N/A', max_length=50, null=True, verbose_name='invoice ref')),
                ('Customer', models.CharField(default='N/A', max_length=50, null=True, verbose_name='customer')),
                ('InvoiceDate', models.DateField(null=True)),
                ('Paid', models.BooleanField(default=True, null=True, verbose_name='paid')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(default='N/A', max_length=255, null=True, verbose_name='company name')),
                ('StreetAddress', models.CharField(default='N/A', max_length=255, null=True, verbose_name='street address')),
                ('City', models.CharField(default='N/A', max_length=255, null=True, verbose_name='city')),
                ('State', models.CharField(default='N/A', max_length=50, null=True, verbose_name='state')),
                ('ZipCode', models.CharField(default='N/A', max_length=50, null=True, verbose_name='zip code')),
                ('PhoneNumber', models.CharField(default='N/A', max_length=50, null=True, verbose_name='phone number')),
                ('EmailAddress', models.CharField(default='N/A', max_length=255, null=True, verbose_name='email')),
                ('TaxIDNumber', models.CharField(default='N/A', max_length=50, null=True, verbose_name='tax id')),
                ('Fax', models.CharField(default='N/A', max_length=50, null=True, verbose_name='Fax')),
                ('Client', models.CharField(default='N/A', max_length=50, null=True, verbose_name='client')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ZipCode', models.CharField(default='N/A', max_length=50, null=True, verbose_name='ZipCode')),
                ('PlaceName', models.CharField(default='N/A', max_length=50, null=True, verbose_name='PlaceName')),
                ('StateAbreviation', models.CharField(default='N/A', max_length=50, null=True, verbose_name='StateAbreviation')),
                ('County', models.CharField(default='N/A', max_length=50, null=True, verbose_name='County')),
                ('Latitude', models.CharField(default='N/A', max_length=50, null=True, verbose_name='Latitude')),
                ('Longitude', models.CharField(default='N/A', max_length=50, null=True, verbose_name='Longitude')),
                ('StateTax', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='StateTax')),
                ('LocalTax', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='LocalTax')),
                ('TotalTax', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='TotalTax')),
                ('FiscalDate', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
    ]
