# Generated by Django 2.1.15 on 2020-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_Codes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(null=True)),
                ('charge_code', models.CharField(default='N/A', max_length=100, null=True, verbose_name='charge')),
                ('vendor_id', models.IntegerField(null=True)),
                ('service_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='service type')),
                ('active_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(null=True)),
                ('charge_id', models.IntegerField(null=True)),
                ('vendor_id', models.IntegerField(null=True)),
                ('resource_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource type')),
                ('service_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='service type')),
                ('service_provider', models.CharField(default='N/A', max_length=100, null=True, verbose_name='service provider')),
                ('cost_type', models.CharField(default='N/A', max_length=100, null=True, verbose_name='cost type')),
                ('item_date', models.DateField(null=True)),
                ('item_desc', models.CharField(default='N/A', max_length=100, null=True, verbose_name='item description')),
                ('rate', models.FloatField(null=True, verbose_name='rate')),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.FloatField(null=True, verbose_name='total')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiceID',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='CustomerID',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='InvoiceID',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='ResourceName',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='StaffID',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ChargeCode',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='InvoiceDate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ResourceDept',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ResourceID',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ResourceType',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Total',
        ),
    ]
