# Generated by Django 2.1.15 on 2020-12-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20201213_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge_codes',
            old_name='vendor_id',
            new_name='contractor_id',
        ),
    ]
