# Generated by Django 2.1.15 on 2020-12-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_charge_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_item',
            old_name='vendor_id',
            new_name='contractor_id',
        ),
    ]
