# Generated by Django 2.1.15 on 2020-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20201217_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
    ]
