# Generated by Django 2.1.15 on 2020-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20201215_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge_codes',
            old_name='contractor_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='invoice_item',
            old_name='customer_id',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='charge_codes',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='charge_codes',
            name='charge_desc',
            field=models.CharField(default='N/A', max_length=255, null=True, verbose_name='charge'),
        ),
        migrations.AlterField(
            model_name='chargecodes',
            name='Customer',
            field=models.CharField(default='N/A', max_length=100, null=True, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='contractor_quoteid',
            name='Customer',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='client'),
        ),
    ]
