# Generated by Django 2.1.15 on 2020-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice_item_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='client_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice_id',
            field=models.IntegerField(null=True),
        ),
    ]
