# Generated by Django 2.1.15 on 2020-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20201218_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceItem_id', models.IntegerField(null=True)),
                ('client_id', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('staff_id', models.IntegerField(null=True)),
                ('invoice_desc', models.CharField(default='N/A', max_length=100, null=True, verbose_name='invoice_desc')),
                ('charge_code', models.CharField(default='N/A', max_length=100, null=True, verbose_name='resource name')),
                ('paid', models.BooleanField(default=True, null=True, verbose_name='paid')),
                ('payment_date', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('backup_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
